#!/bin/bash

firewall-cmd --zone=external --new-service=ssa2lxc --permanent
firewall-cmd --zone=external --add-service=ssa2lxc --permanent
firewall-cmd --zone=dmz --add-service=ssa2lxc --permanent
firewall-cmd --zone=external --add-service=http --permanent
firewall-cmd --zone=external --add-service=https --permanent
firewall-cmd --zone=external --add-masquerade --permanent
firewall-cmd --zone=external --add-port=8640/tcp --permanent
firewall-cmd --zone=dmz --add-service=dhcp --permanent
firewall-cmd --zone=dmz --add-service=dns --permanent
firewall-cmd --zone=external --change-interface=eth0 --permanent
firewall-cmd --zone=dmz --change-interface=rfapp0
firewall-cmd --zone=dmz --change-interface=rfapp0 --permanent
firewall-cmd --zone=dmz --change-interface=cfapp0 --permanent
firewall-cmd --zone=dmz --change-interface=ccapp0 --permanent
firewall-cmd --zone=dmz --change-interface=cmsapp0 --permanent
firewall-cmd --zone=dmz --change-interface=dbapp0 --permanent
firewall-cmd --zone=dmz --change-interface=vpnapp0 --permanent
firewall-cmd --zone=dmz --change-interface=cfweb0 --permanent
firewall-cmd --zone=external --add-forward-port=port=4101:proto=tcp:toport=22:toaddr=10.0.4.101 --permanent
firewall-cmd --zone=external --add-forward-port=port=4201:proto=tcp:toport=22:toaddr=10.0.4.201 --permanent
firewall-cmd --zone=external --add-forward-port=port=4102:proto=tcp:toport=22:toaddr=10.0.4.102 --permanent
firewall-cmd --zone=external --add-forward-port=port=481:proto=tcp:toport=22:toaddr=10.0.4.81 --permanent
firewall-cmd --zone=external --add-forward-port=port=1250:proto=tcp:toport=1250:toaddr=10.0.4.81 --permanent
firewall-cmd --zone=external --add-forward-port=port=1350:proto=tcp:toport=1350:toaddr=10.0.4.81 --permanent
firewall-cmd --zone=external --add-forward-port=port=321:proto=tcp:toport=22:toaddr=10.0.2.21 --permanent
firewall-cmd --zone=external --add-forward-port=port=331:proto=tcp:toport=22:toaddr=10.0.2.31 --permanent
firewall-cmd --zone=external --add-forward-port=port=341:proto=tcp:toport=22:toaddr=10.0.1.41 --permanent
firewall-cmd --zone=external --add-forward-port=port=351:proto=tcp:toport=22:toaddr=10.0.5.21 --permanent
firewall-cmd --zone=external --add-forward-port=port=391:proto=tcp:toport=22:toaddr=10.0.5.91 --permanent
firewall-cmd --zone=external --add-forward-port=port=392:proto=tcp:toport=22:toaddr=10.0.5.91 --permanent
firewall-cmd --zone=external --add-forward-port=port=141:proto=tcp:toport=22:toaddr=10.0.1.41 --permanent
firewall-cmd --zone=external --add-forward-port=port=221:proto=tcp:toport=22:toaddr=10.0.2.21 --permanent
firewall-cmd --zone=external --add-forward-port=port=3101:proto=tcp:toport=22:toaddr=10.0.3.101 --permanent
firewall-cmd --zone=external --add-forward-port=port=6101:proto=tcp:toport=22:toaddr=10.0.6.101 --permanent
firewall-cmd --zone=external --add-forward-port=port=621:proto=tcp:toport=22:toaddr=10.0.6.21 --permanent
firewall-cmd --zone=external --add-forward-port=port=411:proto=tcp:toport=22:toaddr=10.0.4.11 --permanent
firewall-cmd --zone=external --add-forward-port=port=9443:proto=tcp:toport=443:toaddr=10.0.4.11 --permanent
firewall-cmd --zone=external --add-forward-port=port=495:proto=tcp:toport=22:toaddr=10.0.4.95 --permanent
firewall-cmd --zone=external --add-forward-port=port=9369:proto=tcp:toport=9369:toaddr=10.0.4.95 --permanent
firewall-cmd --zone=external --add-forward-port=port=8369:proto=tcp:toport=443:toaddr=10.0.4.95 --permanent
firewall-cmd --zone=external --add-forward-port=port=591:proto=tcp:toport=22:toaddr=10.0.5.91 --permanent
firewall-cmd --zone=external --add-forward-port=port=592:proto=tcp:toport=22:toaddr=10.0.5.92 --permanent
firewall-cmd --zone=external --add-forward-port=port=593:proto=tcp:toport=22:toaddr=10.0.5.93 --permanent
firewall-cmd --zone=external --add-forward-port=port=594:proto=tcp:toport=22:toaddr=10.0.5.94 --permanent
firewall-cmd --zone=external --add-forward-port=port=4101:proto=tcp:toport=22:toaddr=10.0.4.101 --permanent
firewall-cmd --zone=external --add-forward-port=port=581:proto=tcp:toport=22:toaddr=10.0.5.81 --permanent
firewall-cmd --zone=external --add-forward-port=port=582:proto=tcp:toport=22:toaddr=10.0.5.82 --permanent
firewall-cmd --zone=external --add-forward-port=port=583:proto=tcp:toport=22:toaddr=10.0.5.83 --permanent
firewall-cmd --zone=external --add-forward-port=port=521:proto=tcp:toport=22:toaddr=10.0.5.21 --permanent
firewall-cmd --zone=external --add-forward-port=port=261:proto=tcp:toport=22:toaddr=10.0.2.61 --permanent
firewall-cmd --zone=external --add-forward-port=port=1193:proto=udp:toport=1194:toaddr=10.0.4.201 --permanent
firewall-cmd --zone=external --add-forward-port=port=1194:proto=udp:toport=1194:toaddr=10.0.4.101 --permanent
firewall-cmd --zone=external --add-forward-port=port=1195:proto=udp:toport=1195:toaddr=10.0.4.101 --permanent
firewall-cmd --zone=external --add-forward-port=port=511:proto=tcp:toport=22:toaddr=10.0.5.11 --permanent
firewall-cmd --zone=external --add-forward-port=port=7160:proto=tcp:toport=22:toaddr=10.0.7.160 --permanent
firewall-cmd --zone=external --add-forward-port=port=6379:proto=tcp:toport=6379:toaddr=10.0.5.11 --permanent
firewall-cmd --zone=external --add-forward-port=port=5601:proto=tcp:toport=5601:toaddr=10.0.5.11 --permanent
firewall-cmd --zone=external --add-forward-port=port=8521:proto=tcp:toport=8080:toaddr=10.0.5.21 --permanent
firewall-cmd --zone=external --add-forward-port=port=8121:proto=tcp:toport=8080:toaddr=10.0.1.21 --permanent
firewall-cmd --zone=external --add-forward-port=port=8221:proto=tcp:toport=8080:toaddr=10.0.2.21 --permanent
firewall-cmd --zone=external --add-forward-port=port=1521:proto=tcp:toport=1521:toaddr=10.0.7.160 --permanent
firewall-cmd --permanent --direct --add-rule ipv4 filter FWDO_dmz_allow 1 -j ACCEPT
firewall-cmd --reload
